INSERT INTO models (Name,Value,brandID)
VALUES ('MacBook Air',(SELECT IDENT_CURRENT('models')),1),
('MacBook Pro',(SELECT IDENT_CURRENT('models')),1),
('iMac',(SELECT IDENT_CURRENT('models')),1),
('Mac mini',(SELECT IDENT_CURRENT('models')),1),
('Mac Pro',(SELECT IDENT_CURRENT('models')),1),
('XPS 13',(SELECT IDENT_CURRENT('models')),2),
('XPS 15',(SELECT IDENT_CURRENT('models')),2),
('Alienware Aurora (Desktop)',(SELECT IDENT_CURRENT('models')),2),
('Inspiron 14',(SELECT IDENT_CURRENT('models')),2),
('Latitude 7420',(SELECT IDENT_CURRENT('models')),2),
('Acer Aspire Series',(SELECT IDENT_CURRENT('models')),3),
('Acer Predator (Gaming laptops)',(SELECT IDENT_CURRENT('models')),3),
('Acer Swift',(SELECT IDENT_CURRENT('models')),3),
('Acer Nitro (Gaming desktops)',(SELECT IDENT_CURRENT('models')),3),
('Asus ZenBook Series',(SELECT IDENT_CURRENT('models')),4),
('Asus ROG (Republic of Gamers)',(SELECT IDENT_CURRENT('models')),4),
('Asus TUF Gaming',(SELECT IDENT_CURRENT('models')),4),
('Asus VivoBook',(SELECT IDENT_CURRENT('models')),4),
('Samsung Galaxy Book',(SELECT IDENT_CURRENT('models')),5),
('Samsung Notebook 9 Pro',(SELECT IDENT_CURRENT('models')),5),
('HP Spectre x360',(SELECT IDENT_CURRENT('models')),5),
('HP Envy Series',(SELECT IDENT_CURRENT('models')),5),
('HP Pavilion Series',(SELECT IDENT_CURRENT('models')),5),
('HP Omen (Gaming series)',(SELECT IDENT_CURRENT('models')),6),
('Other',NULL,7)